Controllers/CadastroClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavelaDelivery.Models;

namespace FavelaDelivery.Controllers
{
    public class CadastroClientesController : Controller
    {
        private readonly Context _context;

        public CadastroClientesController(Context context)
        {
            _context = context;
        }

        // GET: CadastroClientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.cadastrocliente.ToListAsync());
        }

        // GET: CadastroClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroCliente = await _context.cadastrocliente
                .FirstOrDefaultAsync(m => m.Idcliente == id);
            if (cadastroCliente == null)
            {
                return NotFound();
            }

            return View(cadastroCliente);
        }

        // GET: CadastroClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastroClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idcliente,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroCliente cadastroCliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cadastroCliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroCliente);
        }

        // GET: CadastroClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroCliente = await _context.cadastrocliente.FindAsync(id);
            if (cadastroCliente == null)
            {
                return NotFound();
            }
            return View(cadastroCliente);
        }

        // POST: CadastroClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idcliente,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroCliente cadastroCliente)
        {
            if (id != cadastroCliente.Idcliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cadastroCliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastroClienteExists(cadastroCliente.Idcliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroCliente);
        }

        // GET: CadastroClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroCliente = await _context.cadastrocliente
                .FirstOrDefaultAsync(m => m.Idcliente == id);
            if (cadastroCliente == null)
            {
                return NotFound();
            }

            return View(cadastroCliente);
        }

        // POST: CadastroClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cadastroCliente = await _context.cadastrocliente.FindAsync(id);
            _context.cadastrocliente.Remove(cadastroCliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CadastroClienteExists(int id)
        {
            return _context.cadastrocliente.Any(e => e.Idcliente == id);
        }
    }
}

Controllers/CadastroEmpreendedorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavelaDelivery.Models;

namespace FavelaDelivery.Controllers
{
    public class CadastroEmpreendedorsController : Controller
    {
        private readonly Context _context;

        public CadastroEmpreendedorsController(Context context)
        {
            _context = context;
        }

        // GET: CadastroEmpreendedors
        public async Task<IActionResult> Index()
        {
            return View(await _context.cadastroempreendedor.ToListAsync());
        }

        // GET: CadastroEmpreendedors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEmpreendedor = await _context.cadastroempreendedor
                .FirstOrDefaultAsync(m => m.Idempreendedor == id);
            if (cadastroEmpreendedor == null)
            {
                return NotFound();
            }

            return View(cadastroEmpreendedor);
        }

        // GET: CadastroEmpreendedors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastroEmpreendedors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idempreendedor,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroEmpreendedor cadastroEmpreendedor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cadastroEmpreendedor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroEmpreendedor);
        }

        // GET: CadastroEmpreendedors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEmpreendedor = await _context.cadastroempreendedor.FindAsync(id);
            if (cadastroEmpreendedor == null)
            {
                return NotFound();
            }
            return View(cadastroEmpreendedor);
        }

        // POST: CadastroEmpreendedors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idempreendedor,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroEmpreendedor cadastroEmpreendedor)
        {
            if (id != cadastroEmpreendedor.Idempreendedor)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cadastroEmpreendedor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastroEmpreendedorExists(cadastroEmpreendedor.Idempreendedor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroEmpreendedor);
        }

        // GET: CadastroEmpreendedors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEmpreendedor = await _context.cadastroempreendedor
                .FirstOrDefaultAsync(m => m.Idempreendedor == id);
            if (cadastroEmpreendedor == null)
            {
                return NotFound();
            }

            return View(cadastroEmpreendedor);
        }

        // POST: CadastroEmpreendedors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cadastroEmpreendedor = await _context.cadastroempreendedor.FindAsync(id);
            _context.cadastroempreendedor.Remove(cadastroEmpreendedor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CadastroEmpreendedorExists(int id)
        {
            return _context.cadastroempreendedor.Any(e => e.Idempreendedor == id);
        }
    }
}

Controllers/CadastroEntregadorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FavelaDelivery.Models;

namespace FavelaDelivery.Controllers
{
    public class CadastroEntregadorsController : Controller
    {
        private readonly Context _context;

        public CadastroEntregadorsController(Context context)
        {
            _context = context;
        }

        // GET: CadastroEntregadors
        public async Task<IActionResult> Index()
        {
            return View(await _context.cadastroentregador.ToListAsync());
        }

        // GET: CadastroEntregadors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEntregador = await _context.cadastroentregador
                .FirstOrDefaultAsync(m => m.Identregador == id);
            if (cadastroEntregador == null)
            {
                return NotFound();
            }

            return View(cadastroEntregador);
        }

        // GET: CadastroEntregadors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CadastroEntregadors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Identregador,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroEntregador cadastroEntregador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cadastroEntregador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroEntregador);
        }

        // GET: CadastroEntregadors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEntregador = await _context.cadastroentregador.FindAsync(id);
            if (cadastroEntregador == null)
            {
                return NotFound();
            }
            return View(cadastroEntregador);
        }

        // POST: CadastroEntregadors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Identregador,NomeCompleto,CPF,EnderecoPersonalizado,Email,Telefone,Login,Senha")] CadastroEntregador cadastroEntregador)
        {
            if (id != cadastroEntregador.Identregador)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cadastroEntregador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CadastroEntregadorExists(cadastroEntregador.Identregador))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cadastroEntregador);
        }

        // GET: CadastroEntregadors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cadastroEntregador = await _context.cadastroentregador
                .FirstOrDefaultAsync(m => m.Identregador == id);
            if (cadastroEntregador == null)
            {
                return NotFound();
            }

            return View(cadastroEntregador);
        }

        // POST: CadastroEntregadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cadastroEntregador = await _context.cadastroentregador.FindAsync(id);
            _context.cadastroentregador.Remove(cadastroEntregador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CadastroEntregadorExists(int id)
        {
            return _context.cadastroentregador.Any(e => e.Identregador == id);
        }
    }
}

Controllers/HomeController.cs
using FavelaDelivery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FavelaDelivery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("Index");
        }
        public IActionResult Cdastro()
        {
            return View("Cdastro");
        }
        public IActionResult Pedidos()
        {
            return View("Pedidos");
        }
        public IActionResult Quemsomos()
        {
            return View("Quemsomos");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}

<head>
        <link rel="stylesheet" href="~/css/style.css" />
</head>

 <section class="cadastro">
    <h2>Cadastro</h2>
    <p>
      Escolha seu segmento e faça seu cadastro.
    </p>
    <div class="box-cadastro">
      <div>
        <img src="/img/ft-empreendedor.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Empreendedor</h4>
       <a class="nav-link text-dark" asp-area="" asp-controller="CadastroEmpreendedors" asp-action="Index">Cadastro de Empreendedores</a>
      </div>
      <div>
        <img src="/img/ft-entregador.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Entregador</h4>
         <a class="nav-link text-dark" asp-area="" asp-controller="CadastroEntregadors" asp-action="Index">Cadastro de Entregadores</a>
      </div>
      <div>
        <img src="/img/ft-cliente.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Cliente</h4>
       <a class="nav-link text-dark" asp-area="" asp-controller="CadastroClientes" asp-action="Index">Cadastro de Clientes</a>
      </div>
    </div>
  </section>

Views/Home/Cdastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}


<head>
        <link rel="stylesheet" href="~/css/style.css" />
</head>

  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom static-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="~/img/logo_nova.png" alt="logo Favela Delivery" height="70">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Quemsomos" asp-controller="Home">Quem somos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Pedidos" asp-controller="Home">Pedidos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Cdastro" asp-controller="Home">Cadastro</a>
            </li>            
            <div class="icons">
              <a href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a>
              <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            </div>
          </ul>
        </div>
      </div>
    </nav>

 <section class="cadastro">
    <h2>Cadastro</h2>
    <p>
      Escolha seu segmento e faça seu cadastro.
    </p>
    <div class="box-cadastro">
      <div>
        <img src="/img/ft-empreendedor.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Empreendedor</h4>
      <a class="nav-link text-dark" asp-area="" asp-controller="CadastroEmpreendedors" asp-action="Create"><button class="btn" type="submit">Cadastrar</button></a>      
      </div>
      <div>
        <img src="/img/ft-entregador.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Entregador</h4>
      <a class="nav-link text-dark" asp-area="" asp-controller="CadastroEntregadors" asp-action="Create"><button class="btn" type="submit">Cadastrar</button></a>      
      </div>
      <div>
        <img src="/img/ft-cliente.png" class="alignnone" alt="" width="200" height="150" />
        <h4>Cliente</h4>
      <a class="nav-link text-dark" asp-area="" asp-controller="CadastroClientes" asp-action="Create"><button class="btn" type="submit">Cadastrar</button></a>      
</div>
    </div>
  </section>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    
}

<head>
        <link rel="stylesheet" href="~/css/style.css" />
</head>

  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom static-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="~/img/logo_nova.png" alt="logo Favela Delivery" height="70">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Quemsomos" asp-controller="Home">Quem somos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Pedidos" asp-controller="Home">Pedidos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Cdastro" asp-controller="Home">Cadastro</a>
            </li>            
            <div class="icons">
              <a href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a>
              <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            </div>
          </ul>
        </div>
      </div>
    </nav>


  <main class="banner">
    <div class="container">
      <div class="row-teste">
        <div class="texto-banner">
          <h1 class="titulo-banner" style="text-shadow: 1px 1px 1px #005fb2">APOIE <span class="destaque">A SUA COMUNIDADE!</span> PEÇA DE UM COMERCIANTE LOCAL.</h1>
          <span>
            O serviço ideal para sua necessidade de recebimento de seus produtos em sua comunidade em poucos cliques.
            Cadastre-se grátis e comece a usar agora mesmo. Preços direto no app. Peça em Segundos. Preço Justo. Conte com a
            gente! Cadastre-se agora!
          </span>
          <div class="btn-banner">
            <a href="/html/cadastro.html"><button class="btn btn-primary btn-lg" type="submit">Saiba Mais</button></a>
          </div>
        </div>
        <!-- Div Imagem -->
         <div class="div-foto-banner">
         <img class="foto-banner" src= "~/img/foto-bg-mulher.png" alt="imagem mulher" >
        </div>
      </div>
    </div>
  </main>

Views/Home/Pedidos.cshtml
@{
    ViewData["Title"] = "Pedidos";
}

<head>
        <link rel="stylesheet" href="~/css/style.css" />
</head>
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom static-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="~/img/logo_nova.png" alt="logo Favela Delivery" height="70">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Quemsomos" asp-controller="Home">Quem somos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Pedidos" asp-controller="Home">Pedidos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Cdastro" asp-controller="Home">Cadastro</a>
            </li>            
            <div class="icons">
              <a href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a>
              <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            </div>
          </ul>
        </div>
      </div>
    </nav>
  <section class="pedidos">
    <div class="container">
      <h2>Pedidos</h2>
      <p>Encurtamos distâncias e viabilizamos negócios</p>
      <div class="box-pedidos">
        <div>
          <img src="/img/ft-alimentos.png" class="alignnone" alt="" width="200" height="150" />
          <h4>Alimentos</h4>
          <p>Pizza Família Muçarela</p>
        </div>
        <div>
          <img src="/img/ft-artesanatos.png" class="alignnone" alt="" width="200" height="150" />
          <h4>Artesanatos</h4>
          <p>Bolsa em crochê Azul e Branca</p>
        </div>
        <div>
          <img src="/img/ft-eletronicos.png" class="alignnone" alt="" width="200" height="150" />
          <h4>Eletrônicos</h4>
          <p>
            Tablet, Celular e Relógio Smartwatch
          </p>
        </div>
      </div>

    </div>

  </section>

Views/Home/QuemSomos.cshtml
@{
    ViewData["Title"] = "Quem Somos";
}

<head>
        <link rel="stylesheet" href="~/css/style.css" />
</head>
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom static-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="~/img/logo_nova.png" alt="logo Favela Delivery" height="70">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Quemsomos" asp-controller="Home">Quem somos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Pedidos" asp-controller="Home">Pedidos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" asp-action="Cdastro" asp-controller="Home">Cadastro</a>
            </li>            
            <div class="icons">
              <a href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a>
              <a href="https://www.facebook.com/" target="_blank"><i class="bi bi-facebook"></i></a>
            </div>
          </ul>
        </div>
      </div>
    </nav>
  <main class="container">
    <div class="quemsomos">
      <section class="quemsomos-principal">
        <div class="texto-quemsomos">
          <h1 class="titulo-quemsomos">Quem Somos</h1>
          <span>
            Somos um grupo de alunos da ONG Recode Pro empenhados e em
            desenvolvimento, buscando evolução constante e a primeira oportunidade
            no mercado de trabalho na área de tecnologia, especificamente
            Full-Stack. Nosso projeto é voltado para a inclusão de mulheres
            moradoras de comunidades carentes que estão de certa forma excluídas
            por não conseguirem receber suas encomendas dentro de suas
            comunidades, visto que muitas empresas não conseguem adentrar nas
            comunidades e entregar os produtos dos mesmos. O objetivo é facilitar
            a comercialização de produtos e serviços dentro destas comunidades,
            focando especificamente mulheres que residem dentro destas
            comunidades.
          </span>
          
          <a href="/html/contato.html"><button class=" btn-quemsomos" type="submit">Saiba Mais</button></a>
        </div>
      </section>
      <section class="quemsomos-secundario">
        <div class="video-quemsomos">
          <a href="https://youtu.be/KsF-X2kKFCU" target="_blank"><img src="/img/ft favela.jpg" width="300px"  alt="video" /></a>
        </div>
      </section>
    </div>

  </main>